### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by 9yujin** [bankidz/bankidz-client#106]
### ✅ 공통 TODO

- [ ] 전체 리팩토링
  * type assertion 사용 최소화 ([참고](https://hyunseob.github.io/2017/12/12/typescript-type-inteference-and-type-assertion/))
  * type define 최소화 ([참고](https://www.typescriptlang.org/ko/docs/handbook/utility-types.html))
  * 함수 위치 이동 ([참고](https://stackoverflow.com/questions/46138145/where-should-functions-in-function-components-go))
  * 하위 UI 컴포넌트 분할로 JSX 최소화, 변수명 등 가독성 유념
- [ ] GA
- [ ] 리드미 작성
- [ ] React Query migration
- [ ] 에러처리 with React Query ([참고](http://blog.hwahae.co.kr/all/tech/tech-tech/7867/))
- [ ] ESLint NHN rule 적용
- [ ] 홈화면 알림 내역

### ✅ 성우 TODO
- [ ] 애플 소셜로그인 (빠르면 오늘 늦으면 내일)
- [ ] 부모 완주한 돈길 확인 뷰
- [ ] ---로 만든 border 수정
* React Query 공부 (3~5일)
* 홍보페이지
  * Next.js, SSR, 자동배포
  * 컴포넌트 설계 시 Headless-pattern 적용 ([참고1](https://youtu.be/fR8tsJ2r7Eg), [참고2](https://so-so.dev/react/make-select/))
> 2학기는 제 시간의 1/2은 알고리즘, 1/4은 면접대비, 1/4은 뱅키즈 운영 및 유지보수에 쓸것 같아요. 9월 중순까지는 뱅키즈에 많은 시간을 쓰겠지만 그 후론 지금의 1/4 정도 쓸 수 있을것 같습니다.

### ✅ 규진 TODO
- [x] presigned url
- [x] 가족초대 바텀시트
- [x] 돈길 걷기 마무리
- [x] 마이페이지 수정 뷰 대응
- [ ] 웹뷰 바텀시트 배경 터치 시 아래에 위치한 버튼 클릭 문제
- [ ] 돈길 완주 시 모달 열기
- [ ] 홈 Navbar: 알림 아이콘 추가
- [ ] 마이페이지 Navbar: 설정 아이콘
- [ ] 마이페이지 설정 추가 페이지
- [ ] Apple Id 로그인
- [ ] 마이페이지 서비스 이용방법
- [ ] react transition group
- [ ] ---로 만든 border 수정

**Comment by 24siefil** [comment]
노션 페이지로 모든 데이터 이전해두었습니다.
